let sentences = [
{ cn: "你好", vi: "Xin chào" },
{ cn: "谢谢大家", vi: "Cảm ơn mọi người" },
{ cn: "汉语不太难", vi: "Tiếng Trung không quá khó" },
{ cn: "我喜欢汉语", vi: "Tôi thích tiếng Trung" },
{ cn: "你好吗", vi: "Bạn khỏe không" },
{ cn: "我是老师", vi: "Tôi là giáo viên" },
{ cn: "他是学生", vi: "Anh ấy là học sinh" },
{ cn: "她是老师", vi: "Cô ấy là giáo viên" },
{ cn: "大家好", vi: "Chào mọi người" },
{ cn: "谢谢你", vi: "Cảm ơn bạn" },

{ cn: "我有哥哥", vi: "Tôi có anh trai" },
{ cn: "我有姐姐", vi: "Tôi có chị gái" },
{ cn: "你有弟弟吗", vi: "Bạn có em trai không" },
{ cn: "你有妹妹吗", vi: "Bạn có em gái không" },
{ cn: "他有妻子", vi: "Anh ấy có vợ" },
{ cn: "她有丈夫", vi: "Cô ấy có chồng" },
{ cn: "我妈妈很忙", vi: "Mẹ tôi rất bận" },
{ cn: "我爸爸很好", vi: "Ba tôi rất khỏe" },
{ cn: "哥哥喜欢英语", vi: "Anh trai thích tiếng Anh" },
{ cn: "姐姐学习汉语", vi: "Chị gái học tiếng Trung" },

{ cn: "我在学校学习", vi: "Tôi học ở trường" },
{ cn: "今天上课", vi: "Hôm nay lên lớp" },
{ cn: "明天上课吗", vi: "Ngày mai có lên lớp không" },
{ cn: "老师在学校", vi: "Giáo viên ở trường" },
{ cn: "学生很多", vi: "Học sinh rất đông" },
{ cn: "我喜欢学习", vi: "Tôi thích học tập" },
{ cn: "他去上班", vi: "Anh ấy đi làm" },
{ cn: "她今天上班", vi: "Hôm nay cô ấy đi làm" },
{ cn: "我们在学校见面", vi: "Chúng tôi gặp nhau ở trường" },
{ cn: "老师说汉语", vi: "Giáo viên nói tiếng Trung" },

{ cn: "你叫什么名字", vi: "Bạn tên là gì" },
{ cn: "我叫阿明", vi: "Tôi tên là A Minh" },
{ cn: "你姓什么", vi: "Bạn họ gì" },
{ cn: "我姓阮", vi: "Tôi họ Nguyễn" },
{ cn: "他叫小明", vi: "Anh ấy tên Tiểu Minh" },
{ cn: "她叫什么名字", vi: "Cô ấy tên gì" },
{ cn: "我问老师", vi: "Tôi hỏi giáo viên" },
{ cn: "老师回答我", vi: "Giáo viên trả lời tôi" },
{ cn: "请问你叫什么名字", vi: "Xin hỏi bạn tên gì" },
{ cn: "我叫阿华", vi: "Tôi tên là A Hoa" },

{ cn: "你住在哪里", vi: "Bạn sống ở đâu" },
{ cn: "我住在越南", vi: "Tôi sống ở Việt Nam" },
{ cn: "他住在中国", vi: "Anh ấy sống ở Trung Quốc" },
{ cn: "她住在哪里", vi: "Cô ấy sống ở đâu" },
{ cn: "我们住在这里", vi: "Chúng tôi sống ở đây" },
{ cn: "老师住在河内", vi: "Giáo viên sống ở Hà Nội" },
{ cn: "我喜欢这里", vi: "Tôi thích nơi này" },
{ cn: "你喜欢那里吗", vi: "Bạn thích nơi đó không" },
{ cn: "大家住在哪里", vi: "Mọi người sống ở đâu" },
{ cn: "他们住在中国", vi: "Họ sống ở Trung Quốc" },

{ cn: "今天很忙", vi: "Hôm nay rất bận" },
{ cn: "昨天很忙", vi: "Hôm qua rất bận" },
{ cn: "明天有课", vi: "Ngày mai có lớp học" },
{ cn: "今天学习汉语", vi: "Hôm nay học tiếng Trung" },
{ cn: "昨天我上班", vi: "Hôm qua tôi đi làm" },
{ cn: "明天我回家", vi: "Ngày mai tôi về nhà" },
{ cn: "今天见老师", vi: "Hôm nay gặp giáo viên" },
{ cn: "昨天见朋友", vi: "Hôm qua gặp bạn bè" },
{ cn: "今天我很高兴", vi: "Hôm nay tôi rất vui" },
{ cn: "明天见", vi: "Hẹn gặp ngày mai" },

{ cn: "你结婚了吗", vi: "Bạn kết hôn chưa" },
{ cn: "我还没结婚", vi: "Tôi vẫn chưa kết hôn" },
{ cn: "他结婚了", vi: "Anh ấy đã kết hôn" },
{ cn: "她还没结婚", vi: "Cô ấy vẫn chưa kết hôn" },
{ cn: "哥哥结婚了", vi: "Anh trai đã kết hôn" },
{ cn: "姐姐结婚了吗", vi: "Chị gái kết hôn chưa" },
{ cn: "我问他", vi: "Tôi hỏi anh ấy" },
{ cn: "他说还没", vi: "Anh ấy nói vẫn chưa" },
{ cn: "他们结婚了", vi: "Họ đã kết hôn" },
{ cn: "今天问老师", vi: "Hôm nay hỏi giáo viên" },

{ cn: "我去银行取钱", vi: "Tôi đi ngân hàng rút tiền" },
{ cn: "他去银行", vi: "Anh ấy đi ngân hàng" },
{ cn: "银行很忙", vi: "Ngân hàng rất bận" },
{ cn: "我有很多钱", vi: "Tôi có nhiều tiền" },
{ cn: "她去邮局寄信", vi: "Cô ấy đi bưu điện gửi thư" },
{ cn: "我寄信给朋友", vi: "Tôi gửi thư cho bạn" },
{ cn: "今天去邮局", vi: "Hôm nay đi bưu điện" },
{ cn: "他取钱了吗", vi: "Anh ấy rút tiền chưa" },
{ cn: "我问银行老师", vi: "Tôi hỏi nhân viên ngân hàng" },
{ cn: "邮局在哪里", vi: "Bưu điện ở đâu" },

{ cn: "一加一是二", vi: "Một cộng một bằng hai" },
{ cn: "二加二是四", vi: "Hai cộng hai bằng bốn" },
{ cn: "我有三本书", vi: "Tôi có ba quyển sách" },
{ cn: "他有四个朋友", vi: "Anh ấy có bốn người bạn" },
{ cn: "五个人学习汉语", vi: "Năm người học tiếng Trung" },
{ cn: "六个人上课", vi: "Sáu người lên lớp" },
{ cn: "七个人上班", vi: "Bảy người đi làm" },
{ cn: "八个人见面", vi: "Tám người gặp nhau" },
{ cn: "九个人在学校", vi: "Chín người ở trường" },
{ cn: "十个人说汉语", vi: "Mười người nói tiếng Trung" },

{ cn: "我一百岁", vi: "Tôi một trăm tuổi" },
{ cn: "这里有一百个人", vi: "Ở đây có một trăm người" },
{ cn: "他有一千块钱", vi: "Anh ấy có một nghìn đồng" },
{ cn: "学校有一千学生", vi: "Trường có một nghìn học sinh" },
{ cn: "这里有一万人", vi: "Ở đây có một vạn người" },
{ cn: "大家喜欢汉语", vi: "Mọi người thích tiếng Trung" },
{ cn: "您好吗", vi: "Ngài khỏe không" },
{ cn: "不客气", vi: "Không có gì" },
{ cn: "再见老师", vi: "Tạm biệt giáo viên" },
{ cn: "谢谢您", vi: "Cảm ơn ngài" }
];