let sentences = [
    { cn: "我很好", vi: "Tôi rất khỏe" },
{ cn: "你好", vi: "Xin chào" },
{ cn: "您好", vi: "Chào ngài" },
{ cn: "大家好", vi: "Chào mọi người" },
{ cn: "我说汉语", vi: "Tôi nói tiếng Hán" },
{ cn: "我写汉字", vi: "Tôi viết chữ Hán" },
{ cn: "我学汉语", vi: "Tôi học tiếng Hán" },
{ cn: "我学习汉语", vi: "Tôi học tiếng Hán" },
{ cn: "他说汉语", vi: "Anh ấy nói tiếng Hán" },
{ cn: "她学汉语", vi: "Cô ấy học tiếng Hán" },

{ cn: "我去学校", vi: "Tôi đi trường học" },
{ cn: "他去银行", vi: "Anh ấy đi ngân hàng" },
{ cn: "她去邮局", vi: "Cô ấy đi bưu điện" },
{ cn: "我回学校", vi: "Tôi về trường học" },
{ cn: "我住在中国", vi: "Tôi sống ở Trung Quốc" },
{ cn: "她住在越南", vi: "Cô ấy sống ở Việt Nam" },
{ cn: "我喜欢汉语", vi: "Tôi thích tiếng Hán" },
{ cn: "我喜欢学习汉语", vi: "Tôi thích học tiếng Hán" },
{ cn: "他很忙", vi: "Anh ấy rất bận" },
{ cn: "她不忙", vi: "Cô ấy không bận" },

{ cn: "今天上课", vi: "Hôm nay lên lớp" },
{ cn: "今天上班", vi: "Hôm nay đi làm" },
{ cn: "明天上课", vi: "Ngày mai lên lớp" },
{ cn: "明天上班", vi: "Ngày mai đi làm" },
{ cn: "去年学汉语", vi: "Năm trước học tiếng Hán" },
{ cn: "今年学习汉语", vi: "Năm nay học tiếng Hán" },
{ cn: "明年学汉语", vi: "Năm sau học tiếng Hán" },
{ cn: "今天星期日", vi: "Hôm nay là Chủ nhật" },
{ cn: "我问老师", vi: "Tôi hỏi giáo viên" },
{ cn: "请问贵姓", vi: "Xin hỏi quý danh" },

{ cn: "这是谁", vi: "Đây là ai" },
{ cn: "那是谁", vi: "Kia là ai" },
{ cn: "他是老师", vi: "Anh ấy là giáo viên" },
{ cn: "她是老师", vi: "Cô ấy là giáo viên" },
{ cn: "这是杂志", vi: "Đây là tạp chí" },
{ cn: "那是书", vi: "Kia là sách" },
{ cn: "请进", vi: "Mời vào" },
{ cn: "请坐", vi: "Mời ngồi" },
{ cn: "请问", vi: "Xin hỏi" },
{ cn: "不客气", vi: "Không có gì" },

{ cn: "我有朋友", vi: "Tôi có bạn" },
{ cn: "他有女朋友", vi: "Anh ấy có bạn gái" },
{ cn: "她有男朋友", vi: "Cô ấy có bạn trai" },
{ cn: "我家有爸爸妈妈", vi: "Nhà tôi có bố mẹ" },
{ cn: "我有哥哥", vi: "Tôi có anh trai" },
{ cn: "我有弟弟", vi: "Tôi có em trai" },
{ cn: "我有姐姐", vi: "Tôi có chị gái" },
{ cn: "我有妹妹", vi: "Tôi có em gái" },
{ cn: "他有哥哥", vi: "Anh ấy có anh trai" },
{ cn: "她有妹妹", vi: "Cô ấy có em gái" },

{ cn: "我吃米饭", vi: "Tôi ăn cơm" },
{ cn: "我吃包子", vi: "Tôi ăn bánh bao" },
{ cn: "他吃饺子", vi: "Anh ấy ăn sủi cảo" },
{ cn: "她吃面条", vi: "Cô ấy ăn mì sợi" },
{ cn: "我吃鱼", vi: "Tôi ăn cá" },
{ cn: "我吃肉", vi: "Tôi ăn thịt" },
{ cn: "我喝汤", vi: "Tôi uống canh" },
{ cn: "我很饿", vi: "Tôi rất đói" },
{ cn: "我很饱", vi: "Tôi rất no" },
{ cn: "他要米饭", vi: "Anh ấy muốn cơm" },

{ cn: "现在几点", vi: "Bây giờ mấy giờ" },
{ cn: "我六点起床", vi: "Tôi thức dậy lúc 6 giờ" },
{ cn: "我十点睡觉", vi: "Tôi đi ngủ lúc 10 giờ" },
{ cn: "上午上课", vi: "Buổi sáng lên lớp" },
{ cn: "下午上班", vi: "Buổi chiều đi làm" },
{ cn: "中午吃饭", vi: "Buổi trưa ăn cơm" },
{ cn: "我买苹果", vi: "Tôi mua táo" },
{ cn: "她卖水果", vi: "Cô ấy bán trái cây" },
{ cn: "苹果很贵", vi: "Táo rất đắt" },
{ cn: "苹果很便宜", vi: "Táo rất rẻ" },

{ cn: "一公斤苹果多少元", vi: "Một ký táo bao nhiêu tệ" },
{ cn: "一斤苹果多少块", vi: "Một cân táo bao nhiêu tệ" },
{ cn: "我买很多苹果", vi: "Tôi mua nhiều táo" },
{ cn: "我买很少苹果", vi: "Tôi mua ít táo" },
{ cn: "我有很多朋友", vi: "Tôi có nhiều bạn bè" },
{ cn: "我有很少朋友", vi: "Tôi có ít bạn bè" },
{ cn: "中国人学习汉语", vi: "Người Trung Quốc học tiếng Hán" },
{ cn: "越南人学习汉语", vi: "Người Việt Nam học tiếng Hán" },
{ cn: "老师说汉语", vi: "Giáo viên nói tiếng Hán" },
{ cn: "朋友学习汉语", vi: "Bạn bè học tiếng Hán" }
];
